name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install pip
        run: |
          python -m pip install --upgrade pip wheel

      - name: Install dependencies
        working-directory: ./tests
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        working-directory: ./tests
        run: |
          pytest

      - name: CodeCov
        uses: codecov/codecov-action@v2
        with:
          files: ./tests/coverage.xml
          fail_ci_if_error: true